force-app/main/default/objects/ShipEngineAuth__c/ShipEngineAuth__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store api key</description>
    <label>ShipEngineAuth</label>
</CustomObject>

force-app/main/default/objects/ShipEngineAuth__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>This object ties the tracking data to relevant business records (e.g., Orders, Opportunities, Lab Orders) and provides a high-level view of the shipment.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SHIP-{00000000}</displayFormat>
        <label>Shipment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <label>Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Providers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Delivery Attempt</fullName>
            </value>
            <value>
                <fullName>Not Yet In System</fullName>
            </value>
            <value>
                <fullName>Delivered To Collection Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Status_Description__c</fullName>
    <label>Status Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Shipping_Providers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DHL</fullName>
    </customValue>
    <customValue>
        <fullName>FEDEX</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>USPS</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Shipping Providers</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/mc_TrackingCallout_Test.cls
@isTest
public class mc_TrackingCallout_Test {
    @testsetup
    public static void setup(){
        ShipEngineAuth__c setting = ShipEngineAuth__c.getOrgDefaults();
        setting.API_Key__c = 'asd';
        upsert setting;    
        
        // Mock HTTP callout response
        

        // Create instance of the class
        
        Shipment__c shipment = new Shipment__c(
        	Carrier__c = 'UPS',
            Status_Code__c = 'UN',
            Status__c = 'Unknown',
            Status_Description__c = 'Unknown',
            Tracking_Number__c = '1Z6Y21Y60300230254'
        );
        
        insert shipment;
    }

    @isTest
    static void testGetTrackingInformation_Success() {
        // Set up the mock response             
        Test.startTest();
       
        
        
        // Mock HTTP callout response
        

        // Create instance of the class
        mc_TrackingCallouts trackingCallouts = new mc_TrackingCallouts();
        Shipment__c shipment =[SELECT Id,Tracking_Number__c,Carrier__c FROM Shipment__c LIMIT 1][0];
        
        
        // Call method
        Test.setMock(HttpCalloutMock.class,new trackingCalloutMock());
        mc_DTO_TrackingDetails trackingDetails = trackingCallouts.getTrackingInformation(shipment.Tracking_Number__c, shipment.Carrier__c);
        
        // Validate the response
        System.assertNotEquals(trackingDetails, null, 'Assert that trackingDetails is not null.');
        //System.assertEquals(trackingDetails.trackingResponse.data.status, 'delivered');
        Test.stopTest();
    }

    @isTest
    static void testGetTrackingInformation_Failure() {
        // Set up the mock response for failure (e.g., 400 status code)
        
        Test.startTest();
        // Mock HTTP callout response
        Test.setMock(HttpCalloutMock.class,new trackingCalloutMock_Failure());

        // Create instance of the class
        mc_TrackingCallouts trackingCallouts = new mc_TrackingCallouts();
        Shipment__c shipment =[SELECT Id,Tracking_Number__c,Carrier__c FROM Shipment__c LIMIT 1][0];
        // Call method
        mc_DTO_TrackingDetails trackingDetails = trackingCallouts.getTrackingInformation(shipment.Tracking_Number__c, shipment.Carrier__c);
        System.debug('from test => '+JSON.serializePretty(trackingDetails));
        // Validate that the error response is captured
        //System.assertNotEquals(trackingDetails.trackingErrorResponse, null);
        System.assertEquals(trackingDetails.trackingErrorResponse.errors.size(), 1, 'Checks that the number of tracking errors is equal to 1.');
        Test.stopTest();
    }
    
   @isTest
    static void testStartTrackingRequest_Success() {
        
        
        Test.startTest();
        // Mock HTTP callout response
        Test.setMock(HttpCalloutMock.class, new webhooksCalloutMock());

        // Create instance of the class
        mc_TrackingCallouts trackingCallouts = new mc_TrackingCallouts();
        
        Shipment__c shipment =[SELECT Id,Tracking_Number__c,Carrier__c FROM Shipment__c LIMIT 1][0];
        // Call method
        mc_DTO_WebhookDetails webhookDetails = trackingCallouts.startTrackingRequest(shipment.Tracking_Number__c, shipment.Carrier__c);
        
        // Validate the response
        //System.assertNotEquals(webhookDetails, null);
        //System.assertEquals(webhookDetails.trackingWebhookCreationResponse.status, 'success');
        Test.stopTest();
    }

    /* @isTest
    static void testSubscribeToTrackingEvents() {
        // Set up the mock response
        HttpResponse mockResponse = new HttpResponse();
        mockResponse.setStatusCode(204);
        
        Test.startTest();
        // Mock HTTP callout response
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(mockResponse));

        // Create instance of the class
        mc_TrackingCallouts trackingCallouts = new mc_TrackingCallouts();
        
        // Call method
       // mc_DTO_WebhookDetails webhookDetails = trackingCallouts.subscribeToTrackingEvents();
        
        // Validate that no error is returned
        //System.assertEquals(webhookDetails.trackingErrorResponse, null);
        Test.stopTest();
    }*/

    // Mock class to simulate HTTP callouts
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        private HttpResponse mockResponse;

        public MockHttpResponseGenerator(HttpResponse mockResponse) {
            this.mockResponse = mockResponse;
        }

        public HttpResponse respond(HttpRequest req) {
            return mockResponse;
        }
    }
}