force-app/main/default/objects/ShipEngineAuth__c/ShipEngineAuth__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store api key</description>
    <label>ShipEngineAuth</label>
</CustomObject>

force-app/main/default/objects/ShipEngineAuth__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Tests/ShipStationAPIKeyControllerTests.cls
@IsTest
public class ShipStationAPIKeyControllerTests {
    /* Test for upserting API key in custom setting. */
    @IsTest
    public static void testUpsertCustomSettingPositive() {
        User testUser = TestFactory.createTestUser(false, 'System Administrator');
        System.runAs(testUser) {
            ShipStationAPIKeyController.saveApiKey('asd');
        }
        Assert.areEqual(
            'asd',
            ShipEngineAuth__c.getOrgDefaults().API_Key__c,
            'Assert that the API key is the same as the API key in the custom setting.'
        );
    }
}