force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>This object ties the tracking data to relevant business records (e.g., Orders, Opportunities, Lab Orders) and provides a high-level view of the shipment.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SHIP-{00000000}</displayFormat>
        <label>Shipment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Events__c/Shipment_Events__c.object-meta.xml
<CustomObject>
    <description>This will store all of the events that come from the webhook for tracking details.</description>
    <label>Shipment Events</label>
    <nameField>
        <displayFormat>SHPE-{000000000}</displayFormat>
        <label>Shipment Events</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Events__c/fields/Event_Code__c.field-meta.xml
<CustomField>
    <fullName>Event_Code__c</fullName>
    <label>Event Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Events__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <label>Event Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Events__c/fields/Occurred_At__c.field-meta.xml
<CustomField>
    <fullName>Occurred_At__c</fullName>
    <label>Occurred At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipment_Events__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipName>ShipmentEvents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tracking_Event__c/Tracking_Event__c.object-meta.xml
<CustomObject>
    <description>This object represents each shipment milestone or event, as detailed in the &quot;events&quot; array.</description>
    <label>Tracking Event</label>
    <nameField>
        <displayFormat>TE-{00000000}</displayFormat>
        <label>Tracking Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracking_Event__c/fields/City_Locality__c.field-meta.xml
<CustomField>
    <fullName>City_Locality__c</fullName>
    <label>City/Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Event__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <label>Event Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Event__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Event__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipName>Shipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tracking_Event__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Repos/ShipmentEventRepo.cls
public with sharing class ShipmentEventRepo extends BaseRepo {
    public ShipmentEventRepo() {
        super(Shipment_Events__c.SObjectType, true);
    }

    public Shipment_Events__c[] fetchShipmentEventsByShipmentId(Id shipmentId) {
        String selectClause = this.calculateSelectClause(
            new Set<String>{
                'Id',
                'Occurred_At__c',
                'Description__c',
                'Event_Code__c',
                'Event_Description__c',
                'City_Locality__c',
                'Postal_Code__c',
                'State_Province__c',
                'Shipment__c',
                'Shipment__r.Tracking_Number__c'
            }
        );
        String fromObj = this.calculateFromClause();
        String whereClause = ' WHERE Shipment__c = :shipmentId';
        String query = selectClause + ' ' + fromObj + ' ' + whereClause;
        return this.fetch(query, new Map<String, Object>{ 'shipmentId' => shipmentId });
    }
}