force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>This object ties the tracking data to relevant business records (e.g., Orders, Opportunities, Lab Orders) and provides a high-level view of the shipment.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SHIP-{00000000}</displayFormat>
        <label>Shipment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Status_Description__c</fullName>
    <label>Status Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Tracking_Master__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tracking Master</label>
    <referenceTo>Tracking_Master__c</referenceTo>
    <relationshipLabel>Shipment</relationshipLabel>
    <relationshipName>Shipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Master__c/Tracking_Master__c.object-meta.xml
<CustomObject>
    <description>This object is a central repository for storing raw data from the webhook and providing a high-level summary of the shipment&apos;s status.</description>
    <label>Tracking Master</label>
    <nameField>
        <displayFormat>TM-{00000000}</displayFormat>
        <label>Tracking Master</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracking_Master__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Tracking Master</relationshipLabel>
    <relationshipName>Tracking_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tracking_Master__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Master__c/fields/Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Status_Description__c</fullName>
    <label>Status Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Master__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Repos/ShipmentRepo.cls
public with sharing class ShipmentRepo extends BaseRepo {
    public ShipmentRepo() {
        super(Shipment__c.SObjectType);
    }

    /* This method is used to upsert a list of Shipment objects. */
    public Database.UpsertResult[] upsertShipments(Shipment__c[] shipments) {
        return this.doUpsert(shipments);
    }

    /* fetchShipmentByTrackingNumber This method will return the Shipment object for the given tracking number */
    public Shipment__c fetchShipmentByTrackingNumber(String trackingNumber) {
        Shipment__c shipment = new Shipment__c();
        Shipment__c[] shipments;
        try {
            shipments = (List<Shipment__c>) fetchShipmentsByTrackingNumbers(new List<String>{ trackingNumber });
        } catch (ListException error) {
            return new Shipment__c();
        }
        shipment = shipments.isEmpty() ? shipment : shipments[0];
        return shipment;
    }

    /* Fetches Shipment by tracking numbers. */
    public Shipment__c[] fetchShipmentsByTrackingNumbers(List<String> trackingNumbers) {
        String selectClause = this.calculateSelectClause(
            new Set<String>{
                'Id',
                'Tracking_Number__c',
                'Status_Code__C',
                'Tracking_Master__c',
                'Shipment__c.Status_Description__c'
            }
        );
        String fromObj = this.calculateFromClause();
        String whereClause = ' WHERE Tracking_Number__c IN :trackingNumbers';
        String query = selectClause + ' ' + fromObj + ' ' + whereClause;
        return fetch(query, new Map<String, Object>{ 'trackingNumbers' => trackingNumbers });
    }
}