force-app/main/default/objects/Tracking_Master__c/Tracking_Master__c.object-meta.xml
<CustomObject>
    <description>This object is a central repository for storing raw data from the webhook and providing a high-level summary of the shipment&apos;s status.</description>
    <label>Tracking Master</label>
    <nameField>
        <displayFormat>TM-{00000000}</displayFormat>
        <label>Tracking Master</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracking_Master__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tracking_Master__c/fields/Webhook_JSON_Body__c.field-meta.xml
<CustomField>
    <fullName>Webhook_JSON_Body__c</fullName>
    <label>Webhook JSON Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/mc_TrackingResource.cls
@RestResource(urlMapping='/tracking/events/*')
global class mc_TrackingResource {

    @HttpPost
    global static void handlePost() {
        try{
            //Get the body and parse with DTO mc_DTO_TrackingResponse
            RestRequest req = RestContext.request;
            Blob body = req.requestBody;
            String bodyString = body.toString();
            mc_DTO_TrackingResponse trackingData = (mc_DTO_TrackingResponse) JSON.deserialize(bodyString, mc_DTO_TrackingResponse.class);

            //Insert the tracking data into Tracking_Master__c
            Tracking_Master__c trackingMaster = new Tracking_Master__c();
            trackingMaster.Tracking_Number__c = trackingData.data.tracking_number;
            trackingMaster.Webhook_JSON_Body__c = truncateJson(minifyJson(bodyString));

            insert trackingMaster;

            RestContext.response.statusCode = 201;
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }

    }

    // Helper method to minify JSON
    private static String minifyJson(String jsonString) {
        try {
            // Deserialize and re-serialize to remove unnecessary characters
            Object jsonObject = JSON.deserializeUntyped(jsonString);
            return JSON.serialize(jsonObject);
        } catch (Exception e) {
            // Log or handle minification error
            return jsonString; // Fallback to raw JSON if an error occurs
        }
    }

    private static String truncateJson(String jsonString) {
        Integer maxLength = 131072; // Max length for Long Text Area
        return jsonString.length() > maxLength ? jsonString.substring(0, maxLength) : jsonString;
    }
}